version: '3.9'

volumes:
  pg-data:
    driver: local

services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "54643243325"
      POSTGRES_USER: "user"
      POSTGRES_DB: "invest-bot"
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  invest-bot:
    container_name: invest-bot
    build:
      context: .
      dockerfile: cmd/invest-bot/Dockerfile
    env_file:
      - cmd/invest-bot/.env
    environment:
      DB_USER: "user"
      DB_HOST: "postgres-db"
      DB_PORT: "5432"
      DB_PASSWORD: "54643243325"
#      GRPC_GO_LOG_SEVERITY_LEVEL: "info" #For GRPC debug
#      GRPC_GO_LOG_VERBOSITY_LEVEL: "99"
      TIN_TOKEN: "YOUR TOKEN"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
    depends_on:
      - postgres-db
    links:
      - postgres-db
    ports:
      - "8017:8017"
